### ISSUE TITLE
why is there no trades in my roblox trade outbound?

### ISSUE THREAD

**Issue by bishzz** [viown/Atomic#2]
why is there no trades in my roblox trade outbound?
and now it keeps crashing pls help me

**Comment by viown** [comment]
Please elaborate

- Make sure you placed your .ROBLOSECURITY cookie in the config
- Make sure your roblox account has premium
- Make sure you own at least 2 or more limited items.

**Comment by bishzz** [comment]
> Please elaborate
> 
> * Make sure you placed your .ROBLOSECURITY cookie in the config
> * Make sure your roblox account has premium
> * Make sure you own at least 2 or more limited items.



> Please elaborate
> 
> * Make sure you placed your .ROBLOSECURITY cookie in the config
> * Make sure your roblox account has premium
> * Make sure you own at least 2 or more limited items.

what if i only have 1 limited?

**Comment by viown** [comment]
It should still be able to trade, but it'll have trouble finding good trades

**Comment by bishzz** [comment]
> It should still be able to trade, but it'll have trouble finding good trades

oh ok but why is it crashing now what should i do

**Comment by viown** [comment]
Is it crashing once you run it, or while it's trading?

**Comment by bishzz** [comment]
> Is it crashing once you run it, or while it's trading?

the first time i opened it, it was working well and then i closed it then after some time i opened it again but it started crashing

**Comment by viown** [comment]
Instead of trying to find the issue I recommend just re-installing or re-compiling Atomic.

It could also be an issue with your config, you can also just get the latest config here: https://raw.githubusercontent.com/viown/Atomic/master/Data/DefaultConfig.cfg

Best of luck

**Comment by bishzz** [comment]
> Instead of trying to find the issue I recommend just re-installing or re-compiling Atomic.
> 
> It could also be an issue with your config, you can also just get the latest config here: https://raw.githubusercontent.com/viown/Atomic/master/Data/DefaultConfig.cfg
> 
> Best of luck

ok thank you
